server:
  port: 8080
  servlet:
    context-path: /api/aggregator-service

spring:
  data:
    mongodb:
      database: health_tech
      uri: mongodb+srv://kavindyarajapakshabcspgd:YLid69KODEIK7RaU@cluster0.ts8wj.mongodb.net/health_tech

  datasource:
    url: jdbc:redshift://default-workgroup.445567117276.eu-north-1.redshift-serverless.amazonaws.com:5439/health_tech
    username: admin
    password: 'FJRFLcbmlm173&&'

  application:
    name: AppointmentSchedulingService
