spring:
  datasource:
    url: jdbc:postgresql://<redshift-cluster-endpoint>:5439/<database>
    username: <your-username>
    password: <your-password>
    driver-class-name: org.postgresql.Driver

  server:
    port: 8080
  servlet:
    context-path: /api/aggregator-service

  data:
    mongodb:
      database: health_sync
      uri: mongodb+srv://foodie:foodie@cluster0.t4mq9fc.mongodb.net/health_sync

  application:
    name: AppointmentSchedulingService
