server:
  port: 8080
  servlet:
    context-path: /api/aggregator-service

spring:
  data:
    mongodb:
      database: health_sync
      uri: mongodb+srv://foodie:foodie@cluster0.t4mq9fc.mongodb.net/health_sync

  datasource:
    url: jdbc:redshift://default-workgroup.445567117276.eu-north-1.redshift-serverless.amazonaws.com:5439/heath_tech
    username: admin
    password: 'FJRFLcbmlm173&&'

  application:
    name: AppointmentSchedulingService
